# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest -v --junitxml=test-reports/report.xml --html=test-reports/report.html
      env:
        SELENIUM_DRIVER_KIND: remote
        WINDOW_RESOLUTION: DESKTOP_1024X768
    - name: Upload test reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
       name: test-reports
       path: test-reports
       
    services:
     headless:
       image: browserless/chrome:latest
       ports:
         - 3000:3000
       
     
